/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registerOrg;
import Dashboard.Dashboard;
import javax.swing.BorderFactory;

/**
 *
 * @author denis
 */
public class registerOrg extends javax.swing.JFrame {
    



    private void addPlaceholder(javax.swing.text.JTextComponent field, String placeholder) {
        field.setText(placeholder);
        field.setForeground(new java.awt.Color(120, 120, 120));

        field.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(new java.awt.Color(120, 120, 120));
                }
            }
        });

    }

    /**
     * Creates new form registerOrg
     */
    public registerOrg() {
        initComponents();


        addPlaceholder(emailInput, "org@gmail.com");
        addPlaceholder(nameInput, "Official name");
        addPlaceholder(typeInput, "e.g. Academic, Cultural");
        addPlaceholder(appointedInput, "Full name of admin officer");

        addPlaceholder(missionInput, "Describe the organization's mission...");
        addPlaceholder(visionInput, "Describe the organization's vision...");
        addPlaceholder(objectives, "List the key objectives...");
        addPlaceholder(targetInput, "Target members...");
        addPlaceholder(proposedInput, "List all officers with positions and names...");
        addPlaceholder(adviserInput, "Faculty adviser name");

        backBtn.setForeground(new java.awt.Color(120, 120, 120));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(new java.awt.Color(28, 94, 56));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(new java.awt.Color(122, 158, 140));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        reg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adviserInput = new javax.swing.JTextField();
        targetInput = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        proposedInput = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        objectives = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        visionInput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        missionInput = new javax.swing.JTextArea();
        typeInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        appointedInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        nameIcon = new javax.swing.JLabel();
        fill = new javax.swing.JLabel();
        missionIcon = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        missionLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        typeIcon = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        appointedIcon = new javax.swing.JLabel();
        appointedLbl = new javax.swing.JLabel();
        emailIcon = new javax.swing.JLabel();
        visionLbl = new javax.swing.JLabel();
        visionIcon = new javax.swing.JLabel();
        objectivesIcon = new javax.swing.JLabel();
        objectivesLbl = new javax.swing.JLabel();
        targetIcon = new javax.swing.JLabel();
        targetLbl = new javax.swing.JLabel();
        proposedIcon = new javax.swing.JLabel();
        proposedLbl = new javax.swing.JLabel();
        adviserLbl = new javax.swing.JLabel();
        adviserIcon = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1012, 1200));
        jScrollPane1.setViewportView(jPanel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        reg.setForeground(new java.awt.Color(28, 94, 56));
        reg.setText("Register an Organization");
        jPanel1.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 165, 453, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/navBar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        adviserInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        adviserInput.setForeground(new java.awt.Color(28, 94, 56));
        adviserInput.setBorder(null);
        adviserInput.setOpaque(true);
        jPanel1.add(adviserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 1000, 380, 40));

        targetInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        targetInput.setForeground(new java.awt.Color(28, 94, 56));
        targetInput.setBorder(null);
        targetInput.setOpaque(true);
        jPanel1.add(targetInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 730, 380, 40));

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setOpaque(false);

        proposedInput.setColumns(20);
        proposedInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        proposedInput.setForeground(new java.awt.Color(24, 94, 56));
        proposedInput.setLineWrap(true);
        proposedInput.setRows(5);
        proposedInput.setWrapStyleWord(true);
        proposedInput.setBorder(null);
        proposedInput.setMargin(new java.awt.Insets(5, 5, 5, 5));
        proposedInput.setOpaque(false);
        proposedInput.setPreferredSize(new java.awt.Dimension(488, 104));
        jScrollPane5.setViewportView(proposedInput);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 820, 390, 130));

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setOpaque(false);

        objectives.setColumns(20);
        objectives.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        objectives.setForeground(new java.awt.Color(24, 94, 56));
        objectives.setLineWrap(true);
        objectives.setRows(5);
        objectives.setWrapStyleWord(true);
        objectives.setBorder(null);
        objectives.setMargin(new java.awt.Insets(5, 5, 5, 5));
        objectives.setOpaque(false);
        objectives.setPreferredSize(new java.awt.Dimension(490, 104));
        jScrollPane4.setViewportView(objectives);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 585, 390, -1));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setOpaque(false);

        visionInput.setColumns(20);
        visionInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        visionInput.setForeground(new java.awt.Color(24, 94, 56));
        visionInput.setLineWrap(true);
        visionInput.setRows(5);
        visionInput.setWrapStyleWord(true);
        visionInput.setBorder(null);
        visionInput.setMargin(new java.awt.Insets(5, 5, 5, 5));
        visionInput.setOpaque(false);
        visionInput.setPreferredSize(new java.awt.Dimension(490, 104));
        jScrollPane3.setViewportView(visionInput);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 390, 100));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setOpaque(false);

        missionInput.setColumns(20);
        missionInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        missionInput.setForeground(new java.awt.Color(24, 94, 56));
        missionInput.setLineWrap(true);
        missionInput.setRows(5);
        missionInput.setWrapStyleWord(true);
        missionInput.setBorder(null);
        missionInput.setMargin(new java.awt.Insets(5, 5, 5, 5));
        missionInput.setOpaque(false);
        missionInput.setPreferredSize(new java.awt.Dimension(490, 104));
        jScrollPane2.setViewportView(missionInput);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 295, 390, 100));

        typeInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        typeInput.setForeground(new java.awt.Color(28, 94, 56));
        typeInput.setBorder(null);
        typeInput.setOpaque(true);
        jPanel1.add(typeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 465, 430, 40));

        emailInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        emailInput.setForeground(new java.awt.Color(28, 94, 56));
        emailInput.setToolTipText("");
        emailInput.setBorder(null);
        emailInput.setOpaque(true);
        jPanel1.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 298, 430, 40));

        appointedInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        appointedInput.setForeground(new java.awt.Color(28, 94, 56));
        appointedInput.setBorder(null);
        appointedInput.setOpaque(true);
        jPanel1.add(appointedInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 545, 430, 40));

        nameInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        nameInput.setForeground(new java.awt.Color(28, 94, 56));
        nameInput.setBorder(null);
        nameInput.setOpaque(true);
        jPanel1.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 380, 430, 40));

        backBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(122, 158, 140));
        backBtn.setText("< Back");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 30));

        nameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/input.png"))); // NOI18N
        jPanel1.add(nameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 376, -1, -1));

        fill.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        fill.setForeground(new java.awt.Color(122, 158, 140));
        fill.setText("Fill out the form below. Submissions are reviewed by the OSO Admin.");
        jPanel1.add(fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 203, -1, -1));

        missionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/bigTextField.png"))); // NOI18N
        jPanel1.add(missionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 294, -1, -1));

        emailLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(28, 94, 56));
        emailLbl.setText("EMAIL ADDRESS");
        jPanel1.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 272, -1, -1));

        missionLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        missionLbl.setForeground(new java.awt.Color(28, 94, 56));
        missionLbl.setText("MISSION STATEMENT");
        jPanel1.add(missionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 272, 158, -1));

        nameLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(28, 94, 56));
        nameLbl.setText("ORGANIZATION NAME");
        jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 354, 146, -1));

        typeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/input.png"))); // NOI18N
        jPanel1.add(typeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 461, -1, -1));

        typeLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        typeLbl.setForeground(new java.awt.Color(28, 94, 56));
        typeLbl.setText("ORGANIZATION TYPE");
        jPanel1.add(typeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 441, 143, -1));

        appointedIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/input.png"))); // NOI18N
        jPanel1.add(appointedIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 542, -1, -1));

        appointedLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        appointedLbl.setForeground(new java.awt.Color(28, 94, 56));
        appointedLbl.setText("APPOINTED ADMIN");
        jPanel1.add(appointedLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 520, 142, -1));

        emailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/input.png"))); // NOI18N
        jPanel1.add(emailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 294, -1, -1));

        visionLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        visionLbl.setForeground(new java.awt.Color(28, 94, 56));
        visionLbl.setText("VISION STATEMENT");
        jPanel1.add(visionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 416, 158, -1));

        visionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/bigTextField.png"))); // NOI18N
        jPanel1.add(visionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 438, -1, -1));

        objectivesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/bigTextField.png"))); // NOI18N
        jPanel1.add(objectivesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 582, -1, -1));

        objectivesLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        objectivesLbl.setForeground(new java.awt.Color(28, 94, 56));
        objectivesLbl.setText("OBJECTIVES");
        jPanel1.add(objectivesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 560, 158, -1));

        targetIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/smallerInput.png"))); // NOI18N
        jPanel1.add(targetIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 726, -1, -1));

        targetLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        targetLbl.setForeground(new java.awt.Color(28, 94, 56));
        targetLbl.setText("TARGET MEMBERS");
        jPanel1.add(targetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 704, 158, -1));

        proposedIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/biggestInput.png"))); // NOI18N
        jPanel1.add(proposedIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 818, -1, -1));

        proposedLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        proposedLbl.setForeground(new java.awt.Color(28, 94, 56));
        proposedLbl.setText("PROPOSED MEMBERS");
        jPanel1.add(proposedLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 790, 158, -1));

        adviserLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        adviserLbl.setForeground(new java.awt.Color(28, 94, 56));
        adviserLbl.setText("ADVISER");
        jPanel1.add(adviserLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 974, 158, -1));

        adviserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/smallerInput.png"))); // NOI18N
        jPanel1.add(adviserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 996, 448, -1));

        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/submitBtn.png"))); // NOI18N
        submitBtn.setBorder(null);
        submitBtn.setBorderPainted(false);
        submitBtn.setContentAreaFilled(false);
        submitBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/submitHover.png"))); // NOI18N
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 1109, -1, -1));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/cancelBtn.png"))); // NOI18N
        cancelBtn.setBorder(null);
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/cancelHover.png"))); // NOI18N
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 1109, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

  


    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:

          String email = emailInput.getText();
    String name = nameInput.getText();
    String type = typeInput.getText();
    String appointed = appointedInput.getText();

    String mission = missionInput.getText();
    String vision = visionInput.getText();
    String objectivesText = objectives.getText();
    String target = targetInput.getText();
    String proposed = proposedInput.getText();
    String adviser = adviserInput.getText();

    boolean isComplete =
        !email.isEmpty() && !email.equals("org@gmail.com") &&
        !name.isEmpty() && !name.equals("Official name") &&
        !type.isEmpty() && !type.equals("e.g. Academic, Cultural") &&
        !appointed.isEmpty() && !appointed.equals("Full name of admin officer") &&
        !mission.isEmpty() && !mission.contains("Describe") &&
        !vision.isEmpty() && !vision.contains("Describe") &&
        !objectivesText.isEmpty() && !objectivesText.contains("List") &&
        !target.isEmpty() && !target.contains("Target") &&
        !proposed.isEmpty() && !proposed.contains("List") &&
        !adviser.isEmpty() && !adviser.contains("Faculty adviser");

    if (!isComplete) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please complete all fields!");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Submitted successfully!");
    }
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerOrg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adviserIcon;
    private javax.swing.JTextField adviserInput;
    private javax.swing.JLabel adviserLbl;
    private javax.swing.JLabel appointedIcon;
    private javax.swing.JTextField appointedInput;
    private javax.swing.JLabel appointedLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel emailIcon;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel fill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel missionIcon;
    private javax.swing.JTextArea missionInput;
    private javax.swing.JLabel missionLbl;
    private javax.swing.JLabel nameIcon;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextArea objectives;
    private javax.swing.JLabel objectivesIcon;
    private javax.swing.JLabel objectivesLbl;
    private javax.swing.JLabel proposedIcon;
    private javax.swing.JTextArea proposedInput;
    private javax.swing.JLabel proposedLbl;
    private javax.swing.JLabel reg;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel targetIcon;
    private javax.swing.JTextField targetInput;
    private javax.swing.JLabel targetLbl;
    private javax.swing.JLabel typeIcon;
    private javax.swing.JTextField typeInput;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JLabel visionIcon;
    private javax.swing.JTextArea visionInput;
    private javax.swing.JLabel visionLbl;
    // End of variables declaration//GEN-END:variables
}
