/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bond.ui.UserSide;

/**
 *
 * @author denis
 */
public class registerAnOrg extends javax.swing.JFrame {
    
        private void addPlaceholder(javax.swing.text.JTextComponent field, String placeholder) {
        field.setText(placeholder);
        field.setForeground(new java.awt.Color(120, 120, 120));

        field.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(new java.awt.Color(120, 120, 120));
                }
            }
        });
        
         darkPanel.setBackground(new java.awt.Color(0, 0, 0, 150));
        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);
        
        }

    /**
     * Creates new form registerAnOrg
     */
    public registerAnOrg() {
        initComponents();
        
           settingsPanel.setVisible(false);
        
             addPlaceholder(emailInput, "org@gmail.com");
        addPlaceholder(nameInput, "Official name");
        addPlaceholder(typeInput, "e.g. Academic, Cultural");
        addPlaceholder(appointedInput, "Full name of admin officer");

        addPlaceholder(missionInput, "Describe the organization's mission...");
        addPlaceholder(visionInput, "Describe the organization's vision...");
        addPlaceholder(objectives, "List the key objectives...");
        addPlaceholder(targetInput, "Target members...");
        addPlaceholder(proposedInput, "List all officers with positions and names...");
        addPlaceholder(adviserInput, "Faculty adviser name");

        backBtn.setForeground(new java.awt.Color(120, 120, 120));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(new java.awt.Color(28, 94, 56));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(new java.awt.Color(122, 158, 140));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        settings = new javax.swing.JPanel();
        settingsLabel = new javax.swing.JLabel();
        exBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        darkPanel = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        studOrgBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        navbar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        adviserInput = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        proposedInput = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        objectives = new javax.swing.JTextArea();
        targetInput = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        visionInput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        missionInput = new javax.swing.JTextArea();
        appointedInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        typeInput = new javax.swing.JTextField();
        fill = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        settingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(28, 94, 56));

        settingsLabel.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsLabel.setText("SETTINGS");

        exBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/exit_1.png"))); // NOI18N
        exBtn.setBorder(null);
        exBtn.setBorderPainted(false);
        exBtn.setContentAreaFilled(false);
        exBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/exitHover_1.png"))); // NOI18N
        exBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(exBtn)
                .addGap(17, 17, 17))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsLayout.createSequentialGroup()
                        .addComponent(exBtn)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsLayout.createSequentialGroup()
                        .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        settingsPanel.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 250, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/regOrg.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/regOrgHover.png"))); // NOI18N
        settingsPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/login.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/lohinSettingshover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        settingsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, -1));

        jPanel1.add(settingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 210, 600));

        darkPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout darkPanelLayout = new javax.swing.GroupLayout(darkPanel);
        darkPanel.setLayout(darkPanelLayout);
        darkPanelLayout.setHorizontalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        darkPanelLayout.setVerticalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(darkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        dashboardBtn.setBackground(new java.awt.Color(28, 94, 56));
        dashboardBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setText("DASHBOARD");
        dashboardBtn.setBorder(null);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, 30));

        studOrgBtn.setBackground(new java.awt.Color(28, 94, 56));
        studOrgBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        studOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        studOrgBtn.setText("STUDENT ORGS");
        studOrgBtn.setBorder(null);
        studOrgBtn.setBorderPainted(false);
        studOrgBtn.setContentAreaFilled(false);
        studOrgBtn.setFocusPainted(false);
        studOrgBtn.setFocusable(false);
        studOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studOrgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(studOrgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 50));

        aboutBtn.setBackground(new java.awt.Color(28, 94, 56));
        aboutBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("ABOUT");
        aboutBtn.setBorder(null);
        aboutBtn.setBorderPainted(false);
        aboutBtn.setContentAreaFilled(false);
        aboutBtn.setFocusPainted(false);
        aboutBtn.setFocusable(false);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 50));

        settingsBtn.setBackground(new java.awt.Color(28, 94, 56));
        settingsBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        settingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingsBtn.setText("SETTINGS");
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 50));

        navbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/navBar_1.png"))); // NOI18N
        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/submitBtn.png"))); // NOI18N
        submitBtn.setBorder(null);
        submitBtn.setBorderPainted(false);
        submitBtn.setContentAreaFilled(false);
        submitBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/submitHover.png"))); // NOI18N
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 1070, -1, -1));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/cancelBtn.png"))); // NOI18N
        cancelBtn.setBorder(null);
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/cancelHover.png"))); // NOI18N
        jPanel2.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1070, -1, -1));

        adviserInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        adviserInput.setForeground(new java.awt.Color(28, 94, 56));
        adviserInput.setBorder(null);
        adviserInput.setOpaque(true);
        jPanel2.add(adviserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 990, 380, 40));

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setOpaque(false);

        proposedInput.setColumns(20);
        proposedInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        proposedInput.setForeground(new java.awt.Color(24, 94, 56));
        proposedInput.setLineWrap(true);
        proposedInput.setRows(5);
        proposedInput.setWrapStyleWord(true);
        proposedInput.setBorder(null);
        proposedInput.setMargin(new java.awt.Insets(5, 5, 5, 5));
        proposedInput.setOpaque(false);
        proposedInput.setPreferredSize(new java.awt.Dimension(488, 104));
        jScrollPane5.setViewportView(proposedInput);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 800, 390, 130));

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setOpaque(false);

        objectives.setColumns(20);
        objectives.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        objectives.setForeground(new java.awt.Color(24, 94, 56));
        objectives.setLineWrap(true);
        objectives.setRows(5);
        objectives.setWrapStyleWord(true);
        objectives.setBorder(null);
        objectives.setMargin(new java.awt.Insets(5, 5, 5, 5));
        objectives.setOpaque(false);
        objectives.setPreferredSize(new java.awt.Dimension(490, 104));
        jScrollPane4.setViewportView(objectives);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 390, -1));

        targetInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        targetInput.setForeground(new java.awt.Color(28, 94, 56));
        targetInput.setBorder(null);
        targetInput.setOpaque(true);
        jPanel2.add(targetInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 700, 380, 40));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setOpaque(false);

        visionInput.setColumns(20);
        visionInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        visionInput.setForeground(new java.awt.Color(24, 94, 56));
        visionInput.setLineWrap(true);
        visionInput.setRows(5);
        visionInput.setWrapStyleWord(true);
        visionInput.setBorder(null);
        visionInput.setMargin(new java.awt.Insets(5, 5, 5, 5));
        visionInput.setOpaque(false);
        visionInput.setPreferredSize(new java.awt.Dimension(490, 104));
        jScrollPane3.setViewportView(visionInput);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 390, 100));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setOpaque(false);

        missionInput.setColumns(20);
        missionInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        missionInput.setForeground(new java.awt.Color(24, 94, 56));
        missionInput.setLineWrap(true);
        missionInput.setRows(5);
        missionInput.setWrapStyleWord(true);
        missionInput.setBorder(null);
        missionInput.setMargin(new java.awt.Insets(5, 5, 5, 5));
        missionInput.setOpaque(false);
        missionInput.setPreferredSize(new java.awt.Dimension(490, 104));
        jScrollPane2.setViewportView(missionInput);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 390, 100));

        appointedInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        appointedInput.setForeground(new java.awt.Color(28, 94, 56));
        appointedInput.setBorder(null);
        appointedInput.setOpaque(true);
        jPanel2.add(appointedInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 508, 430, 40));

        emailInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        emailInput.setForeground(new java.awt.Color(28, 94, 56));
        emailInput.setToolTipText("");
        emailInput.setBorder(null);
        emailInput.setOpaque(true);
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        jPanel2.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 430, 40));

        nameInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        nameInput.setForeground(new java.awt.Color(28, 94, 56));
        nameInput.setBorder(null);
        nameInput.setOpaque(true);
        jPanel2.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 322, 430, 40));

        typeInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        typeInput.setForeground(new java.awt.Color(28, 94, 56));
        typeInput.setBorder(null);
        typeInput.setOpaque(true);
        jPanel2.add(typeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 417, 430, 40));

        fill.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        fill.setForeground(new java.awt.Color(122, 158, 140));
        fill.setText("Fill out the form below. Submissions are reviewed by the OSO Admin.");
        jPanel2.add(fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        reg.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        reg.setForeground(new java.awt.Color(28, 94, 56));
        reg.setText("Register an Organization");
        jPanel2.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 453, -1));

        backBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(122, 158, 140));
        backBtn.setText("< Back");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/UserImages/RegisteranOrg.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 998, 1130));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
   new dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void studOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studOrgBtnActionPerformed
   new studOrg().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studOrgBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:
           new about().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
 darkPanel.setVisible(true);
        settingsPanel.setVisible(true);
        settingsPanel.setLocation(750, 0);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_backBtnActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:

        String email = emailInput.getText();
        String name = nameInput.getText();
        String type = typeInput.getText();
        String appointed = appointedInput.getText();

        String mission = missionInput.getText();
        String vision = visionInput.getText();
        String objectivesText = objectives.getText();
        String target = targetInput.getText();
        String proposed = proposedInput.getText();
        String adviser = adviserInput.getText();

        boolean isComplete =
        !email.isEmpty() && !email.equals("org@gmail.com") &&
        !name.isEmpty() && !name.equals("Official name") &&
        !type.isEmpty() && !type.equals("e.g. Academic, Cultural") &&
        !appointed.isEmpty() && !appointed.equals("Full name of admin officer") &&
        !mission.isEmpty() && !mission.contains("Describe") &&
        !vision.isEmpty() && !vision.contains("Describe") &&
        !objectivesText.isEmpty() && !objectivesText.contains("List") &&
        !target.isEmpty() && !target.contains("Target") &&
        !proposed.isEmpty() && !proposed.contains("List") &&
        !adviser.isEmpty() && !adviser.contains("Faculty adviser");

        if (!isComplete) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please complete all fields!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Submitted successfully!");
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void exBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exBtnActionPerformed

        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);
    }//GEN-LAST:event_exBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                    new loginChoices().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerAnOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerAnOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerAnOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerAnOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerAnOrg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JTextField adviserInput;
    private javax.swing.JTextField appointedInput;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel darkPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JTextField emailInput;
    private javax.swing.JButton exBtn;
    private javax.swing.JLabel fill;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea missionInput;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel navbar;
    private javax.swing.JTextArea objectives;
    private javax.swing.JTextArea proposedInput;
    private javax.swing.JLabel reg;
    private javax.swing.JPanel settings;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JButton studOrgBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField targetInput;
    private javax.swing.JTextField typeInput;
    private javax.swing.JTextArea visionInput;
    // End of variables declaration//GEN-END:variables
}
