/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bond.ui.osoAdmin;

/**
 *
 * @author denis
 */
public class osoAdminProfile extends javax.swing.JFrame {

    /**
     * Creates new form osoAdminProfile
     */
    public osoAdminProfile() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        loadProfile();
        setupSaveBtn();
        setupExitButton();
    }

    private void loadProfile() {

        try {

            bond.model.OsoAdmin admin = bond.util.SessionManager.getCurrentOsoAdmin();
            fullnameInput.setText(admin.getUsername());
            emailInput.setText(admin.getEmail());
            roleInput.setText("OSO Administrator");
            roleInput.setEditable(false);

        } catch (Exception ex) {
            System.out.println("Load profile error: " + ex.getMessage());
        }
    }

    private void setupSaveBtn() {

        orgInfoBtn.addActionListener(e -> {

            String username = fullnameInput.getText().trim();
            String email = emailInput.getText().trim();

            if (username.isEmpty() || email.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Username and email cannot be empty.");
                return;
            }

            try {

                java.sql.Connection conn = bond.db.DBConnection.getConnection();
                java.sql.PreparedStatement ps = conn.prepareStatement(
                    "UPDATE oso_admin SET username = ?, email = ? WHERE oso_admin_id = ?"
                );
                ps.setString(1, username);
                ps.setString(2, email);
                ps.setInt(3, bond.util.SessionManager.getCurrentOsoAdmin().getOso_admin_id());
                ps.executeUpdate();
                conn.close();
                javax.swing.JOptionPane.showMessageDialog(this, "Profile updated successfully!");

            } catch (Exception ex) {
                System.out.println("Save profile error: " + ex.getMessage());
            }
        });
    }
    
     private void setupExitButton() {

        javax.swing.JButton btnExit = new javax.swing.JButton("Exit Admin");
        btnExit.setFont(new java.awt.Font("Plus Jakarta Sans", java.awt.Font.BOLD, 12));
        btnExit.setForeground(new java.awt.Color(200, 40, 40));
        btnExit.setBackground(new java.awt.Color(248, 250, 249));
        btnExit.setBorderPainted(false);
        btnExit.setFocusPainted(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setBounds(10, 540, 130, 30);
        btnExit.addActionListener(e -> {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, "Exit OSO Admin?", "Exit",
                javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                bond.util.SessionManager.logout();
                new bond.ui.UserSide.loginChoices().setVisible(true);
                this.dispose();
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 150, 30));
        jPanel1.setComponentZOrder(btnExit, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orgInfoBtn = new javax.swing.JButton();
        orgName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fullnameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        roleInput = new javax.swing.JTextField();
        settingsBtn = new javax.swing.JButton();
        adminprofBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        adprof = new javax.swing.JLabel();
        deets = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(248, 250, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/savechangesBtn.png"))); // NOI18N
        orgInfoBtn.setBorder(null);
        orgInfoBtn.setBorderPainted(false);
        orgInfoBtn.setContentAreaFilled(false);
        orgInfoBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/savechangesHover.png"))); // NOI18N
        jPanel1.add(orgInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, -1));

        orgName.setFont(new java.awt.Font("Playfair Display", 1, 20)); // NOI18N
        orgName.setForeground(new java.awt.Color(28, 94, 56));
        orgName.setText("OSO Administrator");
        jPanel1.add(orgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(28, 94, 56));
        jLabel18.setText("Office of Student Organizations");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 20));

        logo.setText("logo");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 50, -1));

        fullnameInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        fullnameInput.setForeground(new java.awt.Color(28, 94, 56));
        fullnameInput.setToolTipText("");
        fullnameInput.setBorder(null);
        fullnameInput.setOpaque(true);
        fullnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameInputActionPerformed(evt);
            }
        });
        jPanel1.add(fullnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 344, 290, 25));

        emailInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        emailInput.setForeground(new java.awt.Color(28, 94, 56));
        emailInput.setToolTipText("");
        emailInput.setBorder(null);
        emailInput.setOpaque(true);
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        jPanel1.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 406, 290, 25));

        roleInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        roleInput.setForeground(new java.awt.Color(28, 94, 56));
        roleInput.setToolTipText("");
        roleInput.setBorder(null);
        roleInput.setOpaque(true);
        roleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleInputActionPerformed(evt);
            }
        });
        jPanel1.add(roleInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 290, 25));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/settingsBtn.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/settingsHover.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        adminprofBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/adminprofBtn.png"))); // NOI18N
        adminprofBtn.setBorder(null);
        adminprofBtn.setBorderPainted(false);
        adminprofBtn.setContentAreaFilled(false);
        adminprofBtn.setFocusable(false);
        adminprofBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/adminprofHover.png"))); // NOI18N
        adminprofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminprofBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        orgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgBtn.png"))); // NOI18N
        orgBtn.setBorder(null);
        orgBtn.setBorderPainted(false);
        orgBtn.setContentAreaFilled(false);
        orgBtn.setFocusable(false);
        orgBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgHover.png"))); // NOI18N
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/dashboardBtn.png"))); // NOI18N
        dashboardBtn.setBorder(null);
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/dashboardHover.png"))); // NOI18N
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/navBar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        adprof.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        adprof.setForeground(new java.awt.Color(28, 94, 56));
        adprof.setText("Admin Profile");
        jPanel1.add(adprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        deets.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        deets.setForeground(new java.awt.Color(28, 94, 56));
        deets.setText("Your OSO admin account details");
        jPanel1.add(deets, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/adminProfileFrame.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/sidebar.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:\

       new osoSettings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void adminprofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofBtnActionPerformed
        // TODO add your handling code here:
        //new adminProfile().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_adminprofBtnActionPerformed

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:

         new osoOrganizations().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
                 new osoDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void fullnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void roleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(osoAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(osoAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(osoAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(osoAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new osoAdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminprofBtn;
    private javax.swing.JLabel adprof;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel deets;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField fullnameInput;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton orgBtn;
    private javax.swing.JButton orgInfoBtn;
    private javax.swing.JLabel orgName;
    private javax.swing.JTextField roleInput;
    private javax.swing.JButton settingsBtn;
    // End of variables declaration//GEN-END:variables
}
