/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bond.ui.osoAdmin;

/**
 *
 * @author denis
 */
public class osoOrganizations extends javax.swing.JFrame {

    /**
     * Creates new form osoOrganizations
     */
    public osoOrganizations() {
        initComponents();
        setLocationRelativeTo(null);
        loadOrganizations();
    }

    private void loadOrganizations() {

        jPanel2.removeAll();

        try {

            java.sql.Connection conn = bond.db.DBConnection.getConnection();
            java.sql.ResultSet rs = conn.prepareStatement("SELECT org_id, org_name, classification, status FROM organization ORDER BY org_name ASC").executeQuery();

            int y = 130;

            while (rs.next()) {

                int id = rs.getInt("org_id");
                String name = rs.getString("org_name");
                String classification = rs.getString("classification");
                String status = rs.getString("status");

                javax.swing.JLabel lblName = new javax.swing.JLabel(name);
                lblName.setFont(new java.awt.Font("Playfair Display", java.awt.Font.BOLD, 18));
                lblName.setForeground(new java.awt.Color(28, 94, 56));
                lblName.setBounds(130, y + 20, 400, 30);
                jPanel2.add(lblName);

                javax.swing.JLabel lblInfo = new javax.swing.JLabel(classification);
                lblInfo.setFont(new java.awt.Font("Plus Jakarta Sans", java.awt.Font.BOLD, 12));
                lblInfo.setForeground(new java.awt.Color(28, 94, 56));
                lblInfo.setBounds(130, y + 50, 400, 20);
                jPanel2.add(lblInfo);

                javax.swing.JLabel lblStatus = new javax.swing.JLabel("●  " + status);
                lblStatus.setForeground(new java.awt.Color(28, 94, 56));
                lblStatus.setBounds(670, y + 40, 100, 20);
                jPanel2.add(lblStatus);

                javax.swing.JButton btn = new javax.swing.JButton();
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgsFrame.png")));
                btn.setBorder(null);
                btn.setBorderPainted(false);
                btn.setContentAreaFilled(false);
                btn.setBounds(30, y, 750, 100);
                final int orgId = id;
                btn.addActionListener(e -> {
                    bond.ui.osoAdmin.osoOrgInfos frame = new bond.ui.osoAdmin.osoOrgInfos(orgId);
                    frame.setVisible(true);
                    this.dispose();
                });
                jPanel2.add(btn);

                y += 110;
            }

            jPanel2.setPreferredSize(new java.awt.Dimension(780, y + 20));
            jPanel2.revalidate();
            jPanel2.repaint();
            conn.close();

        } catch (Exception ex) {
            System.out.println("Load orgs error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        settingsBtn = new javax.swing.JButton();
        adminprofBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        orgName = new javax.swing.JLabel();
        memberCount = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        active = new javax.swing.JLabel();
        orgInfoBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 250, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/navBar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/settingsBtn.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/settingsHover.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        adminprofBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/adminprofBtn.png"))); // NOI18N
        adminprofBtn.setBorder(null);
        adminprofBtn.setBorderPainted(false);
        adminprofBtn.setContentAreaFilled(false);
        adminprofBtn.setFocusable(false);
        adminprofBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/adminprofHover.png"))); // NOI18N
        adminprofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminprofBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        orgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgBtn.png"))); // NOI18N
        orgBtn.setBorder(null);
        orgBtn.setBorderPainted(false);
        orgBtn.setContentAreaFilled(false);
        orgBtn.setFocusable(false);
        orgBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgHover.png"))); // NOI18N
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/dashboardBtn.png"))); // NOI18N
        dashboardBtn.setBorder(null);
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/dashboardHover.png"))); // NOI18N
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/sidebar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 210, 540));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(248, 250, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgName.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        orgName.setForeground(new java.awt.Color(28, 94, 56));
        orgName.setText("POSHED");
        jPanel2.add(orgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 30));

        memberCount.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        memberCount.setForeground(new java.awt.Color(28, 94, 56));
        memberCount.setText("Information Technology · 52 members");
        jPanel2.add(memberCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 20));

        logo.setText("logo here");
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        active.setForeground(new java.awt.Color(28, 94, 56));
        active.setText("●  Active");
        jPanel2.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        orgInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgsFrame.png"))); // NOI18N
        orgInfoBtn.setBorder(null);
        orgInfoBtn.setBorderPainted(false);
        orgInfoBtn.setContentAreaFilled(false);
        orgInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgInfoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(orgInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(28, 94, 56));
        jLabel13.setText("Organizations");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(28, 94, 56));
        jLabel14.setText("Click an organization to view members, posts, and info");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 800, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:\

        new osoSettings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void adminprofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofBtnActionPerformed
        // TODO add your handling code here:
        new osoAdminProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminprofBtnActionPerformed

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:

     new osoOrganizations().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
                 new osoDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void orgInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgInfoBtnActionPerformed
        // TODO add your handling code here:
           new osoOrgInfos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgInfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(osoOrganizations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(osoOrganizations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(osoOrganizations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(osoOrganizations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new osoOrganizations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel active;
    private javax.swing.JButton adminprofBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel memberCount;
    private javax.swing.JButton orgBtn;
    private javax.swing.JButton orgInfoBtn;
    private javax.swing.JLabel orgName;
    private javax.swing.JButton settingsBtn;
    // End of variables declaration//GEN-END:variables
}
