/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bond.ui.osoAdmin;

/**
 *
 * @author denis
 */
public class osoSettings extends javax.swing.JFrame {

    /**
     * Creates new form osoSettings
     */
    public osoSettings() {
        initComponents();
        setLocationRelativeTo(null);
        setupUpdateBtn();
    }

    private void setupUpdateBtn() {

        orgInfoBtn.addActionListener(e -> {

            String currentPass = fullnameInput1.getText().trim();
            String newPass = emailInput1.getText().trim();

            if (currentPass.isEmpty() || newPass.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty.");
                return;
            }

            try {

                int adminId = bond.util.SessionManager.getCurrentOsoAdmin().getOso_admin_id();
                java.sql.Connection conn = bond.db.DBConnection.getConnection();
                java.sql.PreparedStatement ps = conn.prepareStatement(
                    "SELECT password_hash FROM oso_admin WHERE oso_admin_id = ?"
                );
                ps.setInt(1, adminId);
                java.sql.ResultSet rs = ps.executeQuery();

                if (rs.next() && rs.getString("password_hash").equals(currentPass)) {

                    java.sql.PreparedStatement ps2 = conn.prepareStatement(
                        "UPDATE oso_admin SET password_hash = ? WHERE oso_admin_id = ?"
                    );
                    ps2.setString(1, newPass);
                    ps2.setInt(2, adminId);
                    ps2.executeUpdate();
                    javax.swing.JOptionPane.showMessageDialog(this, "Password updated successfully!");
                    fullnameInput1.setText("");
                    emailInput1.setText("");

                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Current password is incorrect.");
                }

                conn.close();

            } catch (Exception ex) {
                System.out.println("Update password error: " + ex.getMessage());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullnameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        orgInfoBtn = new javax.swing.JButton();
        fullnameInput1 = new javax.swing.JTextField();
        emailInput1 = new javax.swing.JTextField();
        settingsBtn = new javax.swing.JButton();
        adminprofBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adprof = new javax.swing.JLabel();
        deets = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        fullnameInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        fullnameInput.setForeground(new java.awt.Color(28, 94, 56));
        fullnameInput.setToolTipText("");
        fullnameInput.setBorder(null);
        fullnameInput.setOpaque(true);
        fullnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameInputActionPerformed(evt);
            }
        });

        emailInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        emailInput.setForeground(new java.awt.Color(28, 94, 56));
        emailInput.setToolTipText("");
        emailInput.setBorder(null);
        emailInput.setOpaque(true);
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 250, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/updatepassBtn.png"))); // NOI18N
        orgInfoBtn.setBorder(null);
        orgInfoBtn.setBorderPainted(false);
        orgInfoBtn.setContentAreaFilled(false);
        orgInfoBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/updatepassHover.png"))); // NOI18N
        jPanel1.add(orgInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        fullnameInput1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        fullnameInput1.setForeground(new java.awt.Color(28, 94, 56));
        fullnameInput1.setToolTipText("");
        fullnameInput1.setBorder(null);
        fullnameInput1.setOpaque(true);
        fullnameInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameInput1ActionPerformed(evt);
            }
        });
        jPanel1.add(fullnameInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 369, 290, 25));

        emailInput1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        emailInput1.setForeground(new java.awt.Color(28, 94, 56));
        emailInput1.setToolTipText("");
        emailInput1.setBorder(null);
        emailInput1.setOpaque(true);
        emailInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInput1ActionPerformed(evt);
            }
        });
        jPanel1.add(emailInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 280, 290, 25));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/settingsBtn.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/settingsHover.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        adminprofBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/adminprofBtn.png"))); // NOI18N
        adminprofBtn.setBorder(null);
        adminprofBtn.setBorderPainted(false);
        adminprofBtn.setContentAreaFilled(false);
        adminprofBtn.setFocusable(false);
        adminprofBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/adminprofHover.png"))); // NOI18N
        adminprofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminprofBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        orgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgBtn.png"))); // NOI18N
        orgBtn.setBorder(null);
        orgBtn.setBorderPainted(false);
        orgBtn.setContentAreaFilled(false);
        orgBtn.setFocusable(false);
        orgBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/orgHover.png"))); // NOI18N
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/dashboardBtn.png"))); // NOI18N
        dashboardBtn.setBorder(null);
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/dashboardHover.png"))); // NOI18N
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/navBar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/sidebar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 210, 540));

        adprof.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        adprof.setForeground(new java.awt.Color(28, 94, 56));
        adprof.setText("Settings ");
        jPanel1.add(adprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        deets.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        deets.setForeground(new java.awt.Color(28, 94, 56));
        deets.setText("Update password");
        jPanel1.add(deets, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bond/assets/OSOimages/passwordUpdateFrame.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:
  new osoOrganizations().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
                 new osoDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void adminprofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofBtnActionPerformed
    new osoAdminProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminprofBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:\

        //new settings().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void fullnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void fullnameInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameInput1ActionPerformed

    private void emailInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInput1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(osoSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(osoSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(osoSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(osoSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new osoSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminprofBtn;
    private javax.swing.JLabel adprof;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel deets;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField emailInput1;
    private javax.swing.JTextField fullnameInput;
    private javax.swing.JTextField fullnameInput1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton orgBtn;
    private javax.swing.JButton orgInfoBtn;
    private javax.swing.JButton settingsBtn;
    // End of variables declaration//GEN-END:variables
}
