package Dashboard;

import java.awt.Color;
import studentOrgs.studOrgs;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author denis
 */
public class Dashboard extends javax.swing.JFrame {

    private void setupHover(javax.swing.JButton btn) {

        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setForeground(java.awt.Color.WHITE);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setForeground(new java.awt.Color(150, 220, 180));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setForeground(java.awt.Color.WHITE);
            }
        });

        darkPanel.setBackground(new java.awt.Color(0, 0, 0, 150));
        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);
    }

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
  settingsPanel.setVisible(false);

       
        searchInput.setOpaque(false);
        searchInput.setBorder(null);
        searchInput.setBackground(new java.awt.Color(0, 0, 0, 0));

       
        javax.swing.JButton[] buttons = {
            dashboardBtn,
            studOrgBtn,
            aboutBtn,
            settingsBtn
        };

        for (javax.swing.JButton btn : buttons) {
            setupHover(btn);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardPanel = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        settingsLabel = new javax.swing.JLabel();
        exBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        darkPanel = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        poshed5 = new javax.swing.JButton();
        poshed4 = new javax.swing.JButton();
        poshed3 = new javax.swing.JButton();
        poshed2 = new javax.swing.JButton();
        poshed1 = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        studOrgBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        bondLabel = new javax.swing.JLabel();
        bondLongLabel = new javax.swing.JLabel();
        discover = new javax.swing.JLabel();
        track = new javax.swing.JLabel();
        university = new javax.swing.JLabel();
        exploreBtn = new javax.swing.JButton();
        searchIcon = new javax.swing.JLabel();
        navIcon = new javax.swing.JLabel();
        darkIcon = new javax.swing.JLabel();
        bulsuIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DashboardPanel.setMinimumSize(new java.awt.Dimension(1000, 600));
        DashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        settingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(28, 94, 56));

        settingsLabel.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsLabel.setText("SETTINGS");

        exBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/exit.png"))); // NOI18N
        exBtn.setBorder(null);
        exBtn.setBorderPainted(false);
        exBtn.setContentAreaFilled(false);
        exBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/exitHover.png"))); // NOI18N
        exBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(exBtn)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(exBtn)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        settingsPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 250, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/regOrg.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/regOrgHover.png"))); // NOI18N
        settingsPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/login.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/loginHover.png"))); // NOI18N
        settingsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, -1));

        DashboardPanel.add(settingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 210, 600));

        darkPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout darkPanelLayout = new javax.swing.GroupLayout(darkPanel);
        darkPanel.setLayout(darkPanelLayout);
        darkPanelLayout.setHorizontalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        darkPanelLayout.setVerticalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        DashboardPanel.add(darkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        searchInput.setBackground(new java.awt.Color(0, 0, 0));
        searchInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchInput.setBorder(null);
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        DashboardPanel.add(searchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        poshed5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshed.png"))); // NOI18N
        poshed5.setBorder(null);
        poshed5.setBorderPainted(false);
        poshed5.setContentAreaFilled(false);
        poshed5.setFocusable(false);
        poshed5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshedHover.png"))); // NOI18N
        DashboardPanel.add(poshed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, -1, -1));

        poshed4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshed.png"))); // NOI18N
        poshed4.setBorder(null);
        poshed4.setBorderPainted(false);
        poshed4.setContentAreaFilled(false);
        poshed4.setFocusPainted(false);
        poshed4.setFocusable(false);
        poshed4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshedHover.png"))); // NOI18N
        poshed4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poshed4ActionPerformed(evt);
            }
        });
        DashboardPanel.add(poshed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        poshed3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshed.png"))); // NOI18N
        poshed3.setBorder(null);
        poshed3.setBorderPainted(false);
        poshed3.setContentAreaFilled(false);
        poshed3.setFocusable(false);
        poshed3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshedHover.png"))); // NOI18N
        DashboardPanel.add(poshed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        poshed2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshed.png"))); // NOI18N
        poshed2.setBorder(null);
        poshed2.setBorderPainted(false);
        poshed2.setContentAreaFilled(false);
        poshed2.setFocusPainted(false);
        poshed2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshedHover.png"))); // NOI18N
        poshed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poshed2ActionPerformed(evt);
            }
        });
        DashboardPanel.add(poshed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, -1, -1));

        poshed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshed.png"))); // NOI18N
        poshed1.setBorder(null);
        poshed1.setBorderPainted(false);
        poshed1.setContentAreaFilled(false);
        poshed1.setFocusPainted(false);
        poshed1.setFocusable(false);
        poshed1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/poshedHover.png"))); // NOI18N
        DashboardPanel.add(poshed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        settingsBtn.setBackground(new java.awt.Color(28, 94, 56));
        settingsBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        settingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingsBtn.setText("SETTINGS");
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        DashboardPanel.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 50));

        aboutBtn.setBackground(new java.awt.Color(28, 94, 56));
        aboutBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("ABOUT");
        aboutBtn.setBorder(null);
        aboutBtn.setBorderPainted(false);
        aboutBtn.setContentAreaFilled(false);
        aboutBtn.setFocusPainted(false);
        aboutBtn.setFocusable(false);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        DashboardPanel.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 50));

        studOrgBtn.setBackground(new java.awt.Color(28, 94, 56));
        studOrgBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        studOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        studOrgBtn.setText("STUDENT ORGS");
        studOrgBtn.setBorder(null);
        studOrgBtn.setBorderPainted(false);
        studOrgBtn.setContentAreaFilled(false);
        studOrgBtn.setFocusPainted(false);
        studOrgBtn.setFocusable(false);
        studOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studOrgBtnActionPerformed(evt);
            }
        });
        DashboardPanel.add(studOrgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 50));

        dashboardBtn.setBackground(new java.awt.Color(28, 94, 56));
        dashboardBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setText("DASHBOARD");
        dashboardBtn.setBorder(null);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        DashboardPanel.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, 30));

        bondLabel.setFont(new java.awt.Font("Playfair Display", 1, 70)); // NOI18N
        bondLabel.setForeground(new java.awt.Color(255, 255, 255));
        bondLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bondLabel.setText("BOND");
        DashboardPanel.add(bondLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 240, 90));

        bondLongLabel.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 22)); // NOI18N
        bondLongLabel.setForeground(new java.awt.Color(255, 255, 255));
        bondLongLabel.setText("Bridging Organizations & Networks for Development");
        DashboardPanel.add(bondLongLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 640, 30));

        discover.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        discover.setForeground(new java.awt.Color(255, 255, 255));
        discover.setText("Discover  campus communities, explore student organizations,");
        DashboardPanel.add(discover, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 460, -1));

        track.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        track.setForeground(new java.awt.Color(255, 255, 255));
        track.setText("track events, and stay connected with everything that shapes  ");
        DashboardPanel.add(track, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        university.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        university.setForeground(new java.awt.Color(255, 255, 255));
        university.setText("your university life.");
        DashboardPanel.add(university, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, -1));

        exploreBtn.setBackground(new java.awt.Color(28, 94, 56));
        exploreBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        exploreBtn.setForeground(new java.awt.Color(255, 255, 255));
        exploreBtn.setText("Explore");
        exploreBtn.setBorder(null);
        exploreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exploreBtnActionPerformed(evt);
            }
        });
        DashboardPanel.add(exploreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 240, 50));

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/searchBar.png"))); // NOI18N
        DashboardPanel.add(searchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        navIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/navBar.png"))); // NOI18N
        DashboardPanel.add(navIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        darkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/dark.png"))); // NOI18N
        DashboardPanel.add(darkIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 80, 1210, 520));

        bulsuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/bulsu.png"))); // NOI18N
        bulsuIcon.setToolTipText("");
        DashboardPanel.add(bulsuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1140, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exploreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploreBtnActionPerformed

        exploreBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 94, 56), 0, true));
    }//GEN-LAST:event_exploreBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed


    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void studOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studOrgBtnActionPerformed

        new studOrgs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studOrgBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_aboutBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed

 darkPanel.setVisible(true);
        settingsPanel.setVisible(true);
        settingsPanel.setLocation(750, 0);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void poshed4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poshed4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poshed4ActionPerformed

    private void poshed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poshed2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poshed2ActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchInputActionPerformed

    private void exBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exBtnActionPerformed

        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);
    }//GEN-LAST:event_exBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JButton aboutBtn;
    private javax.swing.JLabel bondLabel;
    private javax.swing.JLabel bondLongLabel;
    private javax.swing.JLabel bulsuIcon;
    private javax.swing.JLabel darkIcon;
    private javax.swing.JPanel darkPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel discover;
    private javax.swing.JButton exBtn;
    private javax.swing.JButton exploreBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel navIcon;
    private javax.swing.JButton poshed1;
    private javax.swing.JButton poshed2;
    private javax.swing.JButton poshed3;
    private javax.swing.JButton poshed4;
    private javax.swing.JButton poshed5;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JButton studOrgBtn;
    private javax.swing.JLabel track;
    private javax.swing.JLabel university;
    // End of variables declaration//GEN-END:variables

    private void setupDashboardBtn() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
