/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aboutBond;

import Dashboard.Dashboard;
import javax.swing.SwingUtilities;
import loginAdmin.loginAdmin;
import registerOrg.registerOrg;
import studentOrgs.studOrgs;

/**
 *
 * @author denis
 */
public class aboutBOND extends javax.swing.JFrame {

    /**
     * Creates new form registerOrg
     */
    public aboutBOND() {
        initComponents();

        SwingUtilities.invokeLater(() -> {
            jScrollPane1.getVerticalScrollBar().setValue(0);
        });
        searchInput.setOpaque(false);
        searchInput.setBorder(null);
        searchInput.setBackground(new java.awt.Color(0, 0, 0, 0));

        darkPanel.setBackground(new java.awt.Color(0, 0, 0, 150));
        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        settingsLabel = new javax.swing.JLabel();
        exBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        darkPanel = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        settingsBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        studOrgBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reg1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        authors = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bond = new javax.swing.JLabel();
        fill1 = new javax.swing.JLabel();
        aboutAuthors = new javax.swing.JTextArea();
        aboutOrg = new javax.swing.JTextArea();
        aboutBond = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1012, 1200));
        jScrollPane1.setViewportView(jPanel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        settingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(28, 94, 56));

        settingsLabel.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsLabel.setText("SETTINGS");

        exBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/exit.png"))); // NOI18N
        exBtn.setBorder(null);
        exBtn.setBorderPainted(false);
        exBtn.setContentAreaFilled(false);
        exBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/exitHover.png"))); // NOI18N
        exBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(exBtn)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(exBtn)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        settingsPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 250, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/regOrg.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/regOrgHover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        settingsPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/login.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/loginHover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        settingsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, -1));

        jPanel1.add(settingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 210, 600));

        darkPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout darkPanelLayout = new javax.swing.GroupLayout(darkPanel);
        darkPanel.setLayout(darkPanelLayout);
        darkPanelLayout.setHorizontalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        darkPanelLayout.setVerticalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(darkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        searchInput.setBackground(new java.awt.Color(0, 0, 0));
        searchInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchInput.setBorder(null);
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        jPanel1.add(searchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        settingsBtn.setBackground(new java.awt.Color(28, 94, 56));
        settingsBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        settingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingsBtn.setText("SETTINGS");
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 50));

        aboutBtn.setBackground(new java.awt.Color(28, 94, 56));
        aboutBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("ABOUT");
        aboutBtn.setBorder(null);
        aboutBtn.setBorderPainted(false);
        aboutBtn.setContentAreaFilled(false);
        aboutBtn.setFocusPainted(false);
        aboutBtn.setFocusable(false);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 50));

        dashboardBtn.setBackground(new java.awt.Color(28, 94, 56));
        dashboardBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setText("DASHBOARD");
        dashboardBtn.setBorder(null);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, 30));

        studOrgBtn.setBackground(new java.awt.Color(28, 94, 56));
        studOrgBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        studOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        studOrgBtn.setText("STUDENT ORGS");
        studOrgBtn.setBorder(null);
        studOrgBtn.setBorderPainted(false);
        studOrgBtn.setContentAreaFilled(false);
        studOrgBtn.setFocusPainted(false);
        studOrgBtn.setFocusable(false);
        studOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studOrgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(studOrgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutBond/searchBar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        About.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        About.setForeground(new java.awt.Color(28, 94, 56));
        About.setText("About the Organizations");
        jPanel1.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/navBar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        reg1.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        reg1.setForeground(new java.awt.Color(28, 94, 56));
        reg1.setText("About BOND");
        jPanel1.add(reg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 453, -1));

        jSeparator1.setForeground(new java.awt.Color(28, 94, 56));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1000, 20));

        authors.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        authors.setForeground(new java.awt.Color(28, 94, 56));
        authors.setText("About Authors");
        jPanel1.add(authors, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 900, 220, -1));

        jSeparator2.setForeground(new java.awt.Color(28, 94, 56));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 870, 1000, 20));

        bond.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        bond.setForeground(new java.awt.Color(28, 94, 56));
        bond.setText("About BOND");
        jPanel1.add(bond, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 160, -1));

        fill1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        fill1.setForeground(new java.awt.Color(122, 158, 140));
        fill1.setText("Learn more about the platform. the organization, and the people behind it.");
        jPanel1.add(fill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        aboutAuthors.setEditable(false);
        aboutAuthors.setBackground(new java.awt.Color(255, 255, 255));
        aboutAuthors.setColumns(20);
        aboutAuthors.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        aboutAuthors.setForeground(new java.awt.Color(28, 94, 56));
        aboutAuthors.setLineWrap(true);
        aboutAuthors.setRows(5);
        aboutAuthors.setText(" \n        Ang, Denise Rain G. \n\n     Ramirez, Erica Mae DC. \n\n Salamat, Mary Sharmain S. \n\n ");
        aboutAuthors.setAutoscrolls(false);
        aboutAuthors.setBorder(null);
        aboutAuthors.setCaretColor(new java.awt.Color(255, 255, 255));
        aboutAuthors.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutAuthors.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        aboutAuthors.setOpaque(false);
        aboutAuthors.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanel1.add(aboutAuthors, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 970, 230, 160));

        aboutOrg.setEditable(false);
        aboutOrg.setBackground(new java.awt.Color(255, 255, 255));
        aboutOrg.setColumns(20);
        aboutOrg.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        aboutOrg.setForeground(new java.awt.Color(28, 94, 56));
        aboutOrg.setLineWrap(true);
        aboutOrg.setRows(5);
        aboutOrg.setText("The organization serves as a platform that supports students’ academic and personal growth\nthrough various programs and activities. It encourages leadership, collaboration, and active \nparticipation among students. Through its initiatives, it helps students develop  skills and build \nconnections that are valuable for their future careers.");
        aboutOrg.setAutoscrolls(false);
        aboutOrg.setBorder(null);
        aboutOrg.setCaretColor(new java.awt.Color(255, 255, 255));
        aboutOrg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutOrg.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        aboutOrg.setOpaque(false);
        aboutOrg.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanel1.add(aboutOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 810, 130));

        aboutBond.setEditable(false);
        aboutBond.setBackground(new java.awt.Color(255, 255, 255));
        aboutBond.setColumns(20);
        aboutBond.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        aboutBond.setForeground(new java.awt.Color(28, 94, 56));
        aboutBond.setLineWrap(true);
        aboutBond.setRows(5);
        aboutBond.setText("BOND (Bridging Organizations and Networks for Discovery) is a centralized desktop-based system  \ndesigned to organize and manage student organization information. It allows users to explore \norganization profiles,  officer records, and events without requiring login. The system enhances\naccessibility  and transparency by  providing a single, reliable platform for organizational data.");
        aboutBond.setAutoscrolls(false);
        aboutBond.setBorder(null);
        aboutBond.setCaretColor(new java.awt.Color(255, 255, 255));
        aboutBond.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutBond.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        aboutBond.setOpaque(false);
        aboutBond.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanel1.add(aboutBond, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, 860, 130));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studOrgBtnActionPerformed

        new studOrgs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studOrgBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        darkPanel.setVisible(true);
        settingsPanel.setVisible(true);
        settingsPanel.setLocation(750, 0);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_aboutBtnActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void exBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exBtnActionPerformed

        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);
    }//GEN-LAST:event_exBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        new registerOrg().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new loginAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutBOND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutBOND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutBOND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutBOND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutBOND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JTextArea aboutAuthors;
    private javax.swing.JTextArea aboutBond;
    private javax.swing.JButton aboutBtn;
    private javax.swing.JTextArea aboutOrg;
    private javax.swing.JLabel authors;
    private javax.swing.JLabel bond;
    private javax.swing.JPanel darkPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton exBtn;
    private javax.swing.JLabel fill1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel reg1;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JButton studOrgBtn;
    // End of variables declaration//GEN-END:variables
}
