/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osoAdmin;

/**
 *
 * @author denis
 */
public class adminProfile extends javax.swing.JFrame {

    /**
     * Creates new form adminProfile
     */
    public adminProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailInput = new javax.swing.JTextField();
        roleInput = new javax.swing.JTextField();
        fullnameInput = new javax.swing.JTextField();
        savechangesBtn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dasgboardBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        adminprofBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        navbar = new javax.swing.JLabel();
        sideBar = new javax.swing.JLabel();
        adprof = new javax.swing.JLabel();
        deets = new javax.swing.JLabel();
        frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(248, 250, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        emailInput.setForeground(new java.awt.Color(28, 94, 56));
        emailInput.setToolTipText("");
        emailInput.setBorder(null);
        emailInput.setOpaque(true);
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        jPanel1.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 405, 290, 25));

        roleInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        roleInput.setForeground(new java.awt.Color(28, 94, 56));
        roleInput.setToolTipText("");
        roleInput.setBorder(null);
        roleInput.setOpaque(true);
        roleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleInputActionPerformed(evt);
            }
        });
        jPanel1.add(roleInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 290, 25));

        fullnameInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        fullnameInput.setForeground(new java.awt.Color(28, 94, 56));
        fullnameInput.setToolTipText("");
        fullnameInput.setBorder(null);
        fullnameInput.setOpaque(true);
        fullnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameInputActionPerformed(evt);
            }
        });
        jPanel1.add(fullnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 345, 290, 25));

        savechangesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/savechangesBtn.png"))); // NOI18N
        savechangesBtn.setBorder(null);
        savechangesBtn.setBorderPainted(false);
        savechangesBtn.setContentAreaFilled(false);
        savechangesBtn.setFocusable(false);
        savechangesBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/savechangesHover.png"))); // NOI18N
        savechangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savechangesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(savechangesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, 40));

        logo.setText("logo");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Playfair Display", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(28, 94, 56));
        jLabel17.setText("OSO Administrator");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel18.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(28, 94, 56));
        jLabel18.setText("Office of Student Organizations");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 20));

        dasgboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardBtn.png"))); // NOI18N
        dasgboardBtn.setBorder(null);
        dasgboardBtn.setBorderPainted(false);
        dasgboardBtn.setContentAreaFilled(false);
        dasgboardBtn.setFocusable(false);
        dasgboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardHover.png"))); // NOI18N
        dasgboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasgboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dasgboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        orgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgBtn.png"))); // NOI18N
        orgBtn.setBorder(null);
        orgBtn.setBorderPainted(false);
        orgBtn.setContentAreaFilled(false);
        orgBtn.setFocusable(false);
        orgBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgHover.png"))); // NOI18N
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        adminprofBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofBtn.png"))); // NOI18N
        adminprofBtn.setBorder(null);
        adminprofBtn.setBorderPainted(false);
        adminprofBtn.setContentAreaFilled(false);
        adminprofBtn.setFocusable(false);
        adminprofBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofHover.png"))); // NOI18N
        adminprofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminprofBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsBtn.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsHover.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        navbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/navBar.png"))); // NOI18N
        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/sidebar (2).png"))); // NOI18N
        jPanel1.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 560));

        adprof.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        adprof.setForeground(new java.awt.Color(28, 94, 56));
        adprof.setText("Admin Profile");
        jPanel1.add(adprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        deets.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        deets.setForeground(new java.awt.Color(28, 94, 56));
        deets.setText("Your OSO admin account details");
        jPanel1.add(deets, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 20));

        frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminProfileFrame.png"))); // NOI18N
        jPanel1.add(frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dasgboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasgboardBtnActionPerformed
        // TODO add your handling code here:
  new osoAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dasgboardBtnActionPerformed

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:
        new osoOrganizationPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgBtnActionPerformed

    private void adminprofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_adminprofBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
         new settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void savechangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savechangesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savechangesBtnActionPerformed

    private void fullnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameInputActionPerformed

    private void roleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminprofBtn;
    private javax.swing.JLabel adprof;
    private javax.swing.JButton dasgboardBtn;
    private javax.swing.JLabel deets;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel frame;
    private javax.swing.JTextField fullnameInput;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel navbar;
    private javax.swing.JButton orgBtn;
    private javax.swing.JTextField roleInput;
    private javax.swing.JButton savechangesBtn;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel sideBar;
    // End of variables declaration//GEN-END:variables
}
