/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osoAdmin;

import java.awt.CardLayout;

/**
 *
 * @author denis
 */
public class info extends javax.swing.JFrame {

    /**
     * Creates new form info
     */
    public info() {
        initComponents();
        
CardLayout cl = (CardLayout) memberPanel.getLayout();
cl.show(memberPanel, pendingPostPanel.getName());
cl.show(memberPanel, "info"); // default view
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dasgboardBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        adminprofBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        navbar = new javax.swing.JLabel();
        sideBar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        memberPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pendingPostPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pendingpostBtn = new javax.swing.JButton();
        memberBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        active = new javax.swing.JLabel();
        orgName = new javax.swing.JLabel();
        memberCount = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        threeOptionsPanel = new javax.swing.JLabel();

        jLabel13.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(28, 94, 56));
        jLabel13.setText("Organizations");

        jLabel14.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(28, 94, 56));
        jLabel14.setText("Click an organization to view members, posts, and info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(248, 250, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dasgboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardBtn.png"))); // NOI18N
        dasgboardBtn.setBorder(null);
        dasgboardBtn.setBorderPainted(false);
        dasgboardBtn.setContentAreaFilled(false);
        dasgboardBtn.setFocusable(false);
        dasgboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardHover.png"))); // NOI18N
        dasgboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasgboardBtnActionPerformed(evt);
            }
        });
        jPanel2.add(dasgboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        orgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgBtn.png"))); // NOI18N
        orgBtn.setBorder(null);
        orgBtn.setBorderPainted(false);
        orgBtn.setContentAreaFilled(false);
        orgBtn.setFocusable(false);
        orgBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgHover.png"))); // NOI18N
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });
        jPanel2.add(orgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        adminprofBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofBtn.png"))); // NOI18N
        adminprofBtn.setBorder(null);
        adminprofBtn.setBorderPainted(false);
        adminprofBtn.setContentAreaFilled(false);
        adminprofBtn.setFocusable(false);
        adminprofBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofHover.png"))); // NOI18N
        adminprofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofBtnActionPerformed(evt);
            }
        });
        jPanel2.add(adminprofBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsBtn.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsHover.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel2.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        navbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/navBar.png"))); // NOI18N
        jPanel2.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/sidebar (2).png"))); // NOI18N
        jPanel2.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 560));

        jLabel15.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(28, 94, 56));
        jLabel15.setText("Organizations");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(28, 94, 56));
        jLabel16.setText("Click an organization to view members, posts, and info");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 20));

        jPanel3.setBackground(new java.awt.Color(248, 250, 249));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setLayout(new java.awt.CardLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/infoTable.png"))); // NOI18N
        infoPanel.add(jLabel7, "card2");

        memberPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/membersTable.png"))); // NOI18N
        memberPanel.add(jLabel1, "card2");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/pendingTable.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout pendingPostPanelLayout = new javax.swing.GroupLayout(pendingPostPanel);
        pendingPostPanel.setLayout(pendingPostPanelLayout);
        pendingPostPanelLayout.setHorizontalGroup(
            pendingPostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, Short.MAX_VALUE)
        );
        pendingPostPanelLayout.setVerticalGroup(
            pendingPostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pendingPostPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(90, 90, 90))
        );

        memberPanel.add(pendingPostPanel, "card3");

        infoPanel.add(memberPanel, "card3");

        jPanel3.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 660, 200));

        pendingpostBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/pendingBtn.png"))); // NOI18N
        pendingpostBtn.setBorder(null);
        pendingpostBtn.setBorderPainted(false);
        pendingpostBtn.setContentAreaFilled(false);
        pendingpostBtn.setFocusable(false);
        pendingpostBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/pendingHover.png"))); // NOI18N
        pendingpostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendingpostBtnActionPerformed(evt);
            }
        });
        jPanel3.add(pendingpostBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 82, -1, 30));

        memberBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/memberBtn.png"))); // NOI18N
        memberBtn.setBorder(null);
        memberBtn.setBorderPainted(false);
        memberBtn.setContentAreaFilled(false);
        memberBtn.setFocusable(false);
        memberBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/memberHover.png"))); // NOI18N
        memberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberBtnActionPerformed(evt);
            }
        });
        jPanel3.add(memberBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 82, -1, 30));

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/deleteBtn.png"))); // NOI18N
        deleteBtn.setBorder(null);
        deleteBtn.setBorderPainted(false);
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setFocusable(false);
        deleteBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/deleteHover.png"))); // NOI18N
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, 30));

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/infoBtn.png"))); // NOI18N
        infoBtn.setBorder(null);
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.setFocusable(false);
        infoBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/infoHover.png"))); // NOI18N
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });
        jPanel3.add(infoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 82, -1, 30));

        active.setForeground(new java.awt.Color(28, 94, 56));
        active.setText("●  Active");
        jPanel3.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 30));

        orgName.setFont(new java.awt.Font("Playfair Display", 1, 22)); // NOI18N
        orgName.setForeground(new java.awt.Color(28, 94, 56));
        orgName.setText("POSHED");
        jPanel3.add(orgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        memberCount.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 10)); // NOI18N
        memberCount.setForeground(new java.awt.Color(28, 94, 56));
        memberCount.setText("Information Technology · 52 members");
        jPanel3.add(memberCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 20));

        logo.setText("logo here");
        jPanel3.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        threeOptionsPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/whitePanelforOrgs.png"))); // NOI18N
        jPanel3.add(threeOptionsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 730, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dasgboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasgboardBtnActionPerformed
        // TODO add your handling code here:
        
       new osoAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dasgboardBtnActionPerformed

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:
        new osoOrganizationPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgBtnActionPerformed

    private void adminprofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofBtnActionPerformed
        // TODO add your handling code here:
         new adminProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminprofBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
         new settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void memberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberBtnActionPerformed
        // TODO add your handling code here:
        
            CardLayout cl = (CardLayout) memberPanel.getLayout();
    cl.next(memberPanel);
    }//GEN-LAST:event_memberBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_infoBtnActionPerformed

    private void pendingpostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendingpostBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendingpostBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel active;
    private javax.swing.JButton adminprofBtn;
    private javax.swing.JButton dasgboardBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton infoBtn;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logo;
    private javax.swing.JButton memberBtn;
    private javax.swing.JLabel memberCount;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JLabel navbar;
    private javax.swing.JButton orgBtn;
    private javax.swing.JLabel orgName;
    private javax.swing.JPanel pendingPostPanel;
    private javax.swing.JButton pendingpostBtn;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel sideBar;
    private javax.swing.JLabel threeOptionsPanel;
    // End of variables declaration//GEN-END:variables
}
