/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osoAdmin;

/**
 *
 * @author denis
 */
public class osoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form osoAdmin
     */
    public osoAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adminprofBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        dasgboardBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pendingsCOUNT = new javax.swing.JLabel();
        sideBar = new javax.swing.JLabel();
        pendingsIcon = new javax.swing.JLabel();
        eventsCOUNT = new javax.swing.JLabel();
        pendingsPanel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        totalorgIcon = new javax.swing.JLabel();
        eventsIcon = new javax.swing.JLabel();
        eventsPanel = new javax.swing.JLabel();
        totalmemIcon = new javax.swing.JLabel();
        totalOrgsCOUNT = new javax.swing.JLabel();
        totalmemCOUNT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalorgsPanel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totalmemPanel = new javax.swing.JLabel();
        eventsPanel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/scrollableData.png"))); // NOI18N
        jPanel2.add(jLabel2);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 680, 150));

        jPanel1.setBackground(new java.awt.Color(248, 250, 249));
        jPanel1.setForeground(java.awt.SystemColor.control);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/searchBar.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        adminprofBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofBtn.png"))); // NOI18N
        adminprofBtn.setBorder(null);
        adminprofBtn.setBorderPainted(false);
        adminprofBtn.setContentAreaFilled(false);
        adminprofBtn.setFocusable(false);
        adminprofBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofHover.png"))); // NOI18N
        adminprofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminprofBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        orgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgBtn.png"))); // NOI18N
        orgBtn.setBorder(null);
        orgBtn.setBorderPainted(false);
        orgBtn.setContentAreaFilled(false);
        orgBtn.setFocusable(false);
        orgBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgHover.png"))); // NOI18N
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsBtn.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsHover.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        dasgboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardBtn.png"))); // NOI18N
        dasgboardBtn.setBorder(null);
        dasgboardBtn.setBorderPainted(false);
        dasgboardBtn.setContentAreaFilled(false);
        dasgboardBtn.setFocusable(false);
        dasgboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardHover.png"))); // NOI18N
        dasgboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasgboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dasgboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/navBar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel18.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(28, 94, 56));
        jLabel18.setText("Pendings");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, 20));

        pendingsCOUNT.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        pendingsCOUNT.setForeground(new java.awt.Color(28, 94, 56));
        pendingsCOUNT.setText("5");
        jPanel1.add(pendingsCOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 30, 30));

        sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/sidebar (2).png"))); // NOI18N
        jPanel1.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 540));

        pendingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/mdi_account-pending.png"))); // NOI18N
        jPanel1.add(pendingsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, -1));

        eventsCOUNT.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        eventsCOUNT.setForeground(new java.awt.Color(28, 94, 56));
        eventsCOUNT.setText("5");
        jPanel1.add(eventsCOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 30, 30));

        pendingsPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/slot.png"))); // NOI18N
        jPanel1.add(pendingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(28, 94, 56));
        jLabel14.setText("Total Orgs");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 280, -1, 20));

        jLabel19.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(28, 94, 56));
        jLabel19.setText("Events");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, 20));

        totalorgIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/la_university.png"))); // NOI18N
        jPanel1.add(totalorgIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, 20));

        eventsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/mdi_calendar.png"))); // NOI18N
        jPanel1.add(eventsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        eventsPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/regOrgSlot.png"))); // NOI18N
        jPanel1.add(eventsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, 220));

        totalmemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/mdi_people.png"))); // NOI18N
        jPanel1.add(totalmemIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        totalOrgsCOUNT.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        totalOrgsCOUNT.setForeground(new java.awt.Color(28, 94, 56));
        totalOrgsCOUNT.setText("5");
        jPanel1.add(totalOrgsCOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 245, 30, 30));

        totalmemCOUNT.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        totalmemCOUNT.setForeground(new java.awt.Color(28, 94, 56));
        totalmemCOUNT.setText("5");
        jPanel1.add(totalmemCOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 30, 30));

        jLabel9.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(28, 94, 56));
        jLabel9.setText("Total Members");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 20));

        totalorgsPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/slot.png"))); // NOI18N
        jPanel1.add(totalorgsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(28, 94, 56));
        jLabel11.setText("Overview of all student organizations");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 20));

        jLabel12.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(28, 94, 56));
        jLabel12.setText("Dashboard");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        totalmemPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/slot.png"))); // NOI18N
        jPanel1.add(totalmemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        eventsPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/slot.png"))); // NOI18N
        jPanel1.add(eventsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 624));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:\
        
         new settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void dasgboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasgboardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dasgboardBtnActionPerformed

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:
        
          new osoOrganizationPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgBtnActionPerformed

    private void adminprofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofBtnActionPerformed
        // TODO add your handling code here:
        new adminProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminprofBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(osoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(osoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(osoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(osoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new osoAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminprofBtn;
    private javax.swing.JButton dasgboardBtn;
    private javax.swing.JLabel eventsCOUNT;
    private javax.swing.JLabel eventsIcon;
    private javax.swing.JLabel eventsPanel;
    private javax.swing.JLabel eventsPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orgBtn;
    private javax.swing.JLabel pendingsCOUNT;
    private javax.swing.JLabel pendingsIcon;
    private javax.swing.JLabel pendingsPanel;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel sideBar;
    private javax.swing.JLabel totalOrgsCOUNT;
    private javax.swing.JLabel totalmemCOUNT;
    private javax.swing.JLabel totalmemIcon;
    private javax.swing.JLabel totalmemPanel;
    private javax.swing.JLabel totalorgIcon;
    private javax.swing.JLabel totalorgsPanel;
    // End of variables declaration//GEN-END:variables
}
