/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osoAdmin;

/**
 *
 * @author denis
 */
public class settings extends javax.swing.JFrame {

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updatepassBtn = new javax.swing.JButton();
        confirmPassword = new javax.swing.JTextField();
        newPassword = new javax.swing.JTextField();
        navbar = new javax.swing.JLabel();
        dasgboardBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        adminprofBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        adprof = new javax.swing.JLabel();
        deets = new javax.swing.JLabel();
        sideBar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 250, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatepassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/updatepassBtn.png"))); // NOI18N
        updatepassBtn.setBorder(null);
        updatepassBtn.setBorderPainted(false);
        updatepassBtn.setContentAreaFilled(false);
        updatepassBtn.setFocusable(false);
        updatepassBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/updatepassHover.png"))); // NOI18N
        updatepassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepassBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatepassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, 40));

        confirmPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        confirmPassword.setForeground(new java.awt.Color(28, 94, 56));
        confirmPassword.setToolTipText("");
        confirmPassword.setBorder(null);
        confirmPassword.setOpaque(true);
        confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 290, 30));

        newPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        newPassword.setForeground(new java.awt.Color(28, 94, 56));
        newPassword.setToolTipText("");
        newPassword.setBorder(null);
        newPassword.setOpaque(true);
        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 275, 290, 30));

        navbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/navBar.png"))); // NOI18N
        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dasgboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardBtn.png"))); // NOI18N
        dasgboardBtn.setBorder(null);
        dasgboardBtn.setBorderPainted(false);
        dasgboardBtn.setContentAreaFilled(false);
        dasgboardBtn.setFocusable(false);
        dasgboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/dashboardHover.png"))); // NOI18N
        dasgboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasgboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dasgboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        orgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgBtn.png"))); // NOI18N
        orgBtn.setBorder(null);
        orgBtn.setBorderPainted(false);
        orgBtn.setContentAreaFilled(false);
        orgBtn.setFocusable(false);
        orgBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/orgHover.png"))); // NOI18N
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        adminprofBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofBtn.png"))); // NOI18N
        adminprofBtn.setBorder(null);
        adminprofBtn.setBorderPainted(false);
        adminprofBtn.setContentAreaFilled(false);
        adminprofBtn.setFocusable(false);
        adminprofBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/adminprofHover.png"))); // NOI18N
        adminprofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminprofBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsBtn.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/settingsHover.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        adprof.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        adprof.setForeground(new java.awt.Color(28, 94, 56));
        adprof.setText("Settings ");
        jPanel1.add(adprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        deets.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        deets.setForeground(new java.awt.Color(28, 94, 56));
        deets.setText("Update password");
        jPanel1.add(deets, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 20));

        sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/sidebar (2).png"))); // NOI18N
        jPanel1.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osoAdmin/passwordUpdateFrame.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dasgboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasgboardBtnActionPerformed
        // TODO add your handling code here:
          new osoAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dasgboardBtnActionPerformed

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:
        new osoOrganizationPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgBtnActionPerformed

    private void adminprofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofBtnActionPerformed
        // TODO add your handling code here:
         new adminProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminprofBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordActionPerformed

    private void updatepassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepassBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatepassBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminprofBtn;
    private javax.swing.JLabel adprof;
    private javax.swing.JTextField confirmPassword;
    private javax.swing.JButton dasgboardBtn;
    private javax.swing.JLabel deets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel navbar;
    private javax.swing.JTextField newPassword;
    private javax.swing.JButton orgBtn;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel sideBar;
    private javax.swing.JButton updatepassBtn;
    // End of variables declaration//GEN-END:variables
}
