/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentOrgs;

import Dashboard.Dashboard;

/**
 *
 * @author denis
 */
public class studOrgs extends javax.swing.JFrame {

    private void setupHover(javax.swing.JButton btn) {

        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setForeground(java.awt.Color.WHITE);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setForeground(new java.awt.Color(150, 220, 180));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setForeground(java.awt.Color.WHITE);
            }
        });

        darkPanel.setBackground(new java.awt.Color(0, 0, 0, 150));
        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);

    }

    public studOrgs() {
        initComponents();

        settingsPanel.setVisible(false);

        searchInput1.setOpaque(false);
        searchInput1.setBorder(null);
        searchInput1.setBackground(new java.awt.Color(0, 0, 0, 0));

        javax.swing.JButton[] buttons = {
            dashboardBtn1,
            studOrgBtn1,
            aboutBtn1,
            settingsBtn1,};

        for (javax.swing.JButton btn : buttons) {
            setupHover(btn);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchInput = new javax.swing.JTextField();
        searchIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        settingsLabel = new javax.swing.JLabel();
        exBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        darkPanel = new javax.swing.JPanel();
        bitBtn = new javax.swing.JButton();
        bsitBtn = new javax.swing.JButton();
        bsedBtn = new javax.swing.JButton();
        bshmBtn = new javax.swing.JButton();
        bstmBtn = new javax.swing.JButton();
        allBtn = new javax.swing.JButton();
        searchInput1 = new javax.swing.JTextField();
        searchIcon1 = new javax.swing.JLabel();
        dashboardBtn1 = new javax.swing.JButton();
        studOrgBtn1 = new javax.swing.JButton();
        aboutBtn1 = new javax.swing.JButton();
        settingsBtn1 = new javax.swing.JButton();
        explore = new javax.swing.JLabel();
        studOrg = new javax.swing.JLabel();
        navBarIcon1 = new javax.swing.JLabel();
        darkIcon1 = new javax.swing.JLabel();
        bulsuBlur = new javax.swing.JLabel();

        searchInput.setBackground(new java.awt.Color(0, 0, 0));
        searchInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchInput.setBorder(null);
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/searchBar.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        settingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(28, 94, 56));

        settingsLabel.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsLabel.setText("SETTINGS");

        exBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/exit.png"))); // NOI18N
        exBtn.setBorder(null);
        exBtn.setBorderPainted(false);
        exBtn.setContentAreaFilled(false);
        exBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/exitHover.png"))); // NOI18N
        exBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(exBtn)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(exBtn)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        settingsPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 250, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/regOrg.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/regOrgHover.png"))); // NOI18N
        settingsPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/login.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/loginHover.png"))); // NOI18N
        settingsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, -1));

        jPanel1.add(settingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 210, 600));

        darkPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout darkPanelLayout = new javax.swing.GroupLayout(darkPanel);
        darkPanel.setLayout(darkPanelLayout);
        darkPanelLayout.setHorizontalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        darkPanelLayout.setVerticalGroup(
            darkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(darkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        bitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bit.png"))); // NOI18N
        bitBtn.setBorder(null);
        bitBtn.setBorderPainted(false);
        bitBtn.setContentAreaFilled(false);
        bitBtn.setFocusable(false);
        bitBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bitHover.png"))); // NOI18N
        jPanel1.add(bitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        bsitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bsit.png"))); // NOI18N
        bsitBtn.setBorder(null);
        bsitBtn.setBorderPainted(false);
        bsitBtn.setContentAreaFilled(false);
        bsitBtn.setFocusable(false);
        bsitBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bsitHover.png"))); // NOI18N
        jPanel1.add(bsitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        bsedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bsed.png"))); // NOI18N
        bsedBtn.setBorder(null);
        bsedBtn.setBorderPainted(false);
        bsedBtn.setContentAreaFilled(false);
        bsedBtn.setFocusable(false);
        bsedBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bsedHover.png"))); // NOI18N
        jPanel1.add(bsedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        bshmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bshm.png"))); // NOI18N
        bshmBtn.setBorder(null);
        bshmBtn.setBorderPainted(false);
        bshmBtn.setContentAreaFilled(false);
        bshmBtn.setFocusable(false);
        bshmBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bshmHover.png"))); // NOI18N
        jPanel1.add(bshmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

        bstmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bstm.png"))); // NOI18N
        bstmBtn.setBorder(null);
        bstmBtn.setBorderPainted(false);
        bstmBtn.setContentAreaFilled(false);
        bstmBtn.setFocusable(false);
        bstmBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bstmHover.png"))); // NOI18N
        bstmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstmBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bstmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, -1, -1));

        allBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/all.png"))); // NOI18N
        allBtn.setBorder(null);
        allBtn.setBorderPainted(false);
        allBtn.setContentAreaFilled(false);
        allBtn.setFocusable(false);
        allBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/allHover.png"))); // NOI18N
        jPanel1.add(allBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        searchInput1.setBackground(new java.awt.Color(0, 0, 0));
        searchInput1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchInput1.setBorder(null);
        searchInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInput1ActionPerformed(evt);
            }
        });
        jPanel1.add(searchInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        searchIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/searchBar.png"))); // NOI18N
        jPanel1.add(searchIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        dashboardBtn1.setBackground(new java.awt.Color(28, 94, 56));
        dashboardBtn1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        dashboardBtn1.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn1.setText("DASHBOARD");
        dashboardBtn1.setBorder(null);
        dashboardBtn1.setContentAreaFilled(false);
        dashboardBtn1.setFocusPainted(false);
        dashboardBtn1.setFocusable(false);
        dashboardBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, 30));

        studOrgBtn1.setBackground(new java.awt.Color(28, 94, 56));
        studOrgBtn1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        studOrgBtn1.setForeground(new java.awt.Color(255, 255, 255));
        studOrgBtn1.setText("STUDENT ORGS");
        studOrgBtn1.setBorder(null);
        studOrgBtn1.setBorderPainted(false);
        studOrgBtn1.setContentAreaFilled(false);
        studOrgBtn1.setFocusPainted(false);
        studOrgBtn1.setFocusable(false);
        studOrgBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studOrgBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(studOrgBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 50));

        aboutBtn1.setBackground(new java.awt.Color(28, 94, 56));
        aboutBtn1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        aboutBtn1.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn1.setText("ABOUT");
        aboutBtn1.setBorder(null);
        aboutBtn1.setBorderPainted(false);
        aboutBtn1.setContentAreaFilled(false);
        aboutBtn1.setFocusPainted(false);
        aboutBtn1.setFocusable(false);
        aboutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 50));

        settingsBtn1.setBackground(new java.awt.Color(28, 94, 56));
        settingsBtn1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        settingsBtn1.setForeground(new java.awt.Color(255, 255, 255));
        settingsBtn1.setText("SETTINGS");
        settingsBtn1.setBorder(null);
        settingsBtn1.setBorderPainted(false);
        settingsBtn1.setContentAreaFilled(false);
        settingsBtn1.setFocusable(false);
        settingsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 50));

        explore.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        explore.setForeground(new java.awt.Color(255, 255, 255));
        explore.setText("Explore different organizations!");
        jPanel1.add(explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        studOrg.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        studOrg.setForeground(new java.awt.Color(255, 255, 255));
        studOrg.setText("Student Organizations");
        jPanel1.add(studOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 132, 360, 40));

        navBarIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/navBar.png"))); // NOI18N
        jPanel1.add(navBarIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        darkIcon1.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        darkIcon1.setForeground(new java.awt.Color(255, 255, 255));
        darkIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/dark.png"))); // NOI18N
        jPanel1.add(darkIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 80, -1, -1));

        bulsuBlur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentOrgs/bulsuBlur.png"))); // NOI18N
        jPanel1.add(bulsuBlur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtn1ActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtn1ActionPerformed

    private void studOrgBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studOrgBtn1ActionPerformed


    }//GEN-LAST:event_studOrgBtn1ActionPerformed

    private void aboutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtn1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_aboutBtn1ActionPerformed

    private void settingsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtn1ActionPerformed
        darkPanel.setVisible(true);
        settingsPanel.setVisible(true);
        settingsPanel.setLocation(750, 0);
    }//GEN-LAST:event_settingsBtn1ActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void searchInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInput1ActionPerformed

    private void bstmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstmBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bstmBtnActionPerformed

    private void exBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exBtnActionPerformed

        darkPanel.setVisible(false);
        settingsPanel.setVisible(false);
    }//GEN-LAST:event_exBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studOrgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studOrgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studOrgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studOrgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studOrgs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn1;
    private javax.swing.JButton allBtn;
    private javax.swing.JButton bitBtn;
    private javax.swing.JButton bsedBtn;
    private javax.swing.JButton bshmBtn;
    private javax.swing.JButton bsitBtn;
    private javax.swing.JButton bstmBtn;
    private javax.swing.JLabel bulsuBlur;
    private javax.swing.JLabel darkIcon1;
    private javax.swing.JPanel darkPanel;
    private javax.swing.JButton dashboardBtn1;
    private javax.swing.JButton exBtn;
    private javax.swing.JLabel explore;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel navBarIcon1;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JLabel searchIcon1;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTextField searchInput1;
    private javax.swing.JButton settingsBtn1;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JLabel studOrg;
    private javax.swing.JButton studOrgBtn1;
    // End of variables declaration//GEN-END:variables
}
