/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginAdmin;

/**
 *
 * @author denis
 */
public class loginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form loginAdmin
     */
    public loginAdmin() {
        initComponents();

   
        searchInput2.setOpaque(false);
        searchInput2.setBorder(null);
        searchInput2.setBackground(new java.awt.Color(0, 0, 0, 0));

        searchInput2.setText("Search");
        searchInput2.setForeground(new java.awt.Color(120, 120, 120));

        searchInput2.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                if (searchInput2.getText().equals("Search")) {
                    searchInput2.setText("");
                    searchInput2.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (searchInput2.getText().isEmpty()) {
                    searchInput2.setText("Search");
                    searchInput2.setForeground(new java.awt.Color(120, 120, 120));
                }
            }
        });
        
        backBtn.setForeground(java.awt.Color.WHITE);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(new java.awt.Color(28, 94, 56));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(java.awt.Color.WHITE);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchInput2 = new javax.swing.JTextField();
        select = new javax.swing.JLabel();
        osoAdminBtn = new javax.swing.JButton();
        orgAdminBtn = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        searchbar = new javax.swing.JLabel();
        navbar = new javax.swing.JLabel();
        darkIcon = new javax.swing.JLabel();
        bsu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchInput2.setBackground(new java.awt.Color(0, 0, 0));
        searchInput2.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchInput2.setBorder(null);
        searchInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInput2ActionPerformed(evt);
            }
        });
        jPanel1.add(searchInput2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        select.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        select.setForeground(new java.awt.Color(255, 255, 255));
        select.setText("Select your administrator role to continue.");
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 320, -1));

        osoAdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/osoAdminBtn.png"))); // NOI18N
        osoAdminBtn.setBorder(null);
        osoAdminBtn.setBorderPainted(false);
        osoAdminBtn.setContentAreaFilled(false);
        osoAdminBtn.setFocusable(false);
        osoAdminBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/osoAdminHover.png"))); // NOI18N
        osoAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osoAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(osoAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        orgAdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/orgAdminBtn.png"))); // NOI18N
        orgAdminBtn.setBorder(null);
        orgAdminBtn.setBorderPainted(false);
        orgAdminBtn.setContentAreaFilled(false);
        orgAdminBtn.setFocusable(false);
        orgAdminBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/orgAdminHover.png"))); // NOI18N
        orgAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orgAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        loginLabel.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("Login as Admin");
        jPanel1.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 180, 40));

        backBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("< Back");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 30));

        searchbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/searchBar.png"))); // NOI18N
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        navbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/navBar.png"))); // NOI18N
        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        darkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/dark.png"))); // NOI18N
        darkIcon.setText("jLabel5");
        jPanel1.add(darkIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 83, 1330, 520));

        bsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/bulsuBlur.png"))); // NOI18N
        jPanel1.add(bsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orgAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgAdminBtnActionPerformed
        // TODO add your handling code here:

        new OrgAdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orgAdminBtnActionPerformed

    private void osoAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osoAdminBtnActionPerformed
        // TODO add your handling code here:
        
          new OSOAdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_osoAdminBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

   
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInput2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bsu;
    private javax.swing.JLabel darkIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel navbar;
    private javax.swing.JButton orgAdminBtn;
    private javax.swing.JButton osoAdminBtn;
    private javax.swing.JTextField searchInput2;
    private javax.swing.JLabel searchbar;
    private javax.swing.JLabel select;
    // End of variables declaration//GEN-END:variables
}
