/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginAdmin;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 *
 * @author denis
 */
public class OSOAdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form OrgAdminLogin
     */
    public OSOAdminLogin() {
        initComponents();

        searchInput1.setOpaque(false);
        searchInput1.setBorder(null);
        searchInput1.setBackground(new java.awt.Color(0, 0, 0, 0));

        searchInput1.setText("Search");
        searchInput1.setForeground(new java.awt.Color(120, 120, 120));

        searchInput1.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                if (searchInput1.getText().equals("Search")) {
                    searchInput1.setText("");
                    searchInput1.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (searchInput1.getText().isEmpty()) {
                    searchInput1.setText("Search");
                    searchInput1.setForeground(new java.awt.Color(120, 120, 120));
                }
            }
        });

        backBtn.setForeground(java.awt.Color.WHITE);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(new java.awt.Color(28, 94, 56));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtn.setForeground(java.awt.Color.WHITE);
            }
        });

        usernameInput.setOpaque(false);
        usernameInput.setBorder(null);
        usernameInput.setBackground(new java.awt.Color(0, 0, 0, 0));

        usernameInput.setText("Enter your username");
        usernameInput.setForeground(new java.awt.Color(120, 120, 120));

        usernameInput.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                if (usernameInput.getText().equals("Enter your username")) {
                    usernameInput.setText("");
                    usernameInput.setForeground(new java.awt.Color(28, 94, 56));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (usernameInput.getText().isEmpty()) {
                    usernameInput.setText("Enter your username");
                    usernameInput.setForeground(new java.awt.Color(120, 120, 120));
                }
            }
        });

        passwordInput.setText("Enter your password");
        passwordInput.setEchoChar((char) 0); // show text muna
        passwordInput.setForeground(new java.awt.Color(120, 120, 120));

        passwordInput.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                if (String.valueOf(passwordInput.getPassword()).equals("Enter your password")) {
                    passwordInput.setText("");
                    passwordInput.setEchoChar('•'); // hide text
                    passwordInput.setForeground(new java.awt.Color(28, 94, 56)); // green
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (String.valueOf(passwordInput.getPassword()).isEmpty()) {
                    passwordInput.setText("Enter your password");
                    passwordInput.setEchoChar((char) 0); // show placeholder
                    passwordInput.setForeground(new java.awt.Color(120, 120, 120)); // gray
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        searchInput1 = new javax.swing.JTextField();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        searchbar = new javax.swing.JLabel();
        navbar = new javax.swing.JLabel();
        darkIcon = new javax.swing.JLabel();
        bsu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login As OSO Admin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        searchInput1.setBackground(new java.awt.Color(0, 0, 0));
        searchInput1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchInput1.setBorder(null);
        searchInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInput1ActionPerformed(evt);
            }
        });
        jPanel1.add(searchInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        usernameInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        usernameInput.setBorder(null);
        usernameInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        jPanel1.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 252, 420, 40));

        passwordInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        passwordInput.setBorder(null);
        jPanel1.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 332, 420, 40));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/login.png"))); // NOI18N
        login.setBorder(null);
        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/loginHover.png"))); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 100, 30));

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/input.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/input.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        backBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("< Back");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 30));

        searchbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/searchBar.png"))); // NOI18N
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        navbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/navBar.png"))); // NOI18N
        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        darkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/dark.png"))); // NOI18N
        darkIcon.setText("jLabel5");
        jPanel1.add(darkIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 83, 1330, 520));

        bsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAdmin/bulsuBlur.png"))); // NOI18N
        jPanel1.add(bsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        new loginAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed

    }//GEN-LAST:event_usernameInputActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:

        /*String username = usernameInput.getText();
   String password = String.valueOf(passwordInput.getPassword());

    if (savedUsername.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No account found! Please register first.");
        return;
    }

    if (username.equals(savedUsername) && password.equals(savedPassword)) {

        javax.swing.JOptionPane.showMessageDialog(this, "Login Successful!");
        //new Dashboard().setVisible(true);
        this.dispose();

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid credentials!");
    }*/

    }//GEN-LAST:event_loginActionPerformed

    private void searchInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInput1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OSOAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OSOAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OSOAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OSOAdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OSOAdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bsu;
    private javax.swing.JLabel darkIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel navbar;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField searchInput1;
    private javax.swing.JLabel searchbar;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
