/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChoosenOrg;

import aboutBond.*;
import Dashboard.Dashboard;
import javax.swing.SwingUtilities;
import loginAdmin.loginAdmin;
import registerOrg.registerOrg;
import studentOrgs.studOrgs;

/**
 *
 * @author denis
 */
public class choosenOrg extends javax.swing.JFrame {

    /**
     * Creates new form registerOrg
     */
    public choosenOrg() {
        initComponents();

        SwingUtilities.invokeLater(() -> {
            jScrollPane1.getVerticalScrollBar().setValue(0);
        });
        searchInput.setOpaque(false);
        searchInput.setBorder(null);
        searchInput.setBackground(new java.awt.Color(0, 0, 0, 0));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        settingsBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        studOrgBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        authors = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        visionArea = new javax.swing.JTextArea();
        statusLbl = new javax.swing.JLabel();
        bar = new javax.swing.JLabel();
        bulsuBlur = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        eventsLb2 = new javax.swing.JLabel();
        termLbl = new javax.swing.JLabel();
        missionLbl = new javax.swing.JLabel();
        possitionLbl2 = new javax.swing.JLabel();
        missionArea = new javax.swing.JTextArea();
        dateLbl = new javax.swing.JLabel();
        visionLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();
        eventsData = new javax.swing.JLabel();
        eventsLbl1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        officersData = new javax.swing.JLabel();
        possitionLbl1 = new javax.swing.JLabel();
        upcomingBtn = new javax.swing.JButton();
        completedBtn = new javax.swing.JButton();
        allBtn = new javax.swing.JButton();

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/allBtn.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/AllHoverSmall.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1012, 1200));
        jScrollPane1.setViewportView(jPanel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 2250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchInput.setBackground(new java.awt.Color(0, 0, 0));
        searchInput.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchInput.setBorder(null);
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        jPanel1.add(searchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        settingsBtn.setBackground(new java.awt.Color(28, 94, 56));
        settingsBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        settingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingsBtn.setText("SETTINGS");
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setFocusable(false);
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 50));

        aboutBtn.setBackground(new java.awt.Color(28, 94, 56));
        aboutBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("ABOUT");
        aboutBtn.setBorder(null);
        aboutBtn.setBorderPainted(false);
        aboutBtn.setContentAreaFilled(false);
        aboutBtn.setFocusPainted(false);
        aboutBtn.setFocusable(false);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 50));

        dashboardBtn.setBackground(new java.awt.Color(28, 94, 56));
        dashboardBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setText("DASHBOARD");
        dashboardBtn.setBorder(null);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, 30));

        studOrgBtn.setBackground(new java.awt.Color(28, 94, 56));
        studOrgBtn.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        studOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        studOrgBtn.setText("STUDENT ORGS");
        studOrgBtn.setBorder(null);
        studOrgBtn.setBorderPainted(false);
        studOrgBtn.setContentAreaFilled(false);
        studOrgBtn.setFocusPainted(false);
        studOrgBtn.setFocusable(false);
        studOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studOrgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(studOrgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutBond/searchBar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerOrg/navBar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        authors.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        authors.setForeground(new java.awt.Color(28, 94, 56));
        jPanel1.add(authors, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 680, 220, -1));

        jSeparator2.setForeground(new java.awt.Color(28, 94, 56));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1710, 1000, 20));

        visionArea.setEditable(false);
        visionArea.setBackground(new java.awt.Color(255, 255, 255));
        visionArea.setColumns(20);
        visionArea.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        visionArea.setForeground(new java.awt.Color(28, 94, 56));
        visionArea.setLineWrap(true);
        visionArea.setRows(5);
        visionArea.setText(" \nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        visionArea.setAutoscrolls(false);
        visionArea.setBorder(null);
        visionArea.setCaretColor(new java.awt.Color(255, 255, 255));
        visionArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        visionArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        visionArea.setOpaque(false);
        visionArea.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanel1.add(visionArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 940, 830, 190));

        statusLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        statusLbl.setForeground(new java.awt.Color(28, 94, 56));
        statusLbl.setText("STATUS");
        jPanel1.add(statusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 1840, -1, -1));

        bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/bar.png"))); // NOI18N
        jPanel1.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        bulsuBlur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/bulsuBlur.png"))); // NOI18N
        bulsuBlur.setText("jLabel3");
        jPanel1.add(bulsuBlur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        nameLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(28, 94, 56));
        nameLbl.setText("NAME");
        jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1290, -1, -1));

        eventsLb2.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        eventsLb2.setForeground(new java.awt.Color(28, 94, 56));
        eventsLb2.setText("EVENTS");
        jPanel1.add(eventsLb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1840, -1, -1));

        termLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        termLbl.setForeground(new java.awt.Color(28, 94, 56));
        termLbl.setText("TERM");
        jPanel1.add(termLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 1290, -1, -1));

        missionLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        missionLbl.setForeground(new java.awt.Color(28, 94, 56));
        missionLbl.setText("MISSION");
        jPanel1.add(missionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, -1, -1));

        possitionLbl2.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        possitionLbl2.setForeground(new java.awt.Color(28, 94, 56));
        possitionLbl2.setText("POSITION");
        jPanel1.add(possitionLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1290, -1, -1));

        missionArea.setEditable(false);
        missionArea.setBackground(new java.awt.Color(255, 255, 255));
        missionArea.setColumns(20);
        missionArea.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        missionArea.setForeground(new java.awt.Color(28, 94, 56));
        missionArea.setLineWrap(true);
        missionArea.setRows(5);
        missionArea.setText(" \nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        missionArea.setAutoscrolls(false);
        missionArea.setBorder(null);
        missionArea.setCaretColor(new java.awt.Color(255, 255, 255));
        missionArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        missionArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        missionArea.setOpaque(false);
        missionArea.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanel1.add(missionArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, 830, 190));

        dateLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(28, 94, 56));
        dateLbl.setText("DATE");
        jPanel1.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1840, -1, -1));

        visionLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        visionLbl.setForeground(new java.awt.Color(28, 94, 56));
        visionLbl.setText("VISION");
        jPanel1.add(visionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 920, -1, -1));

        locationLbl.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        locationLbl.setForeground(new java.awt.Color(28, 94, 56));
        locationLbl.setText("LOCATION");
        jPanel1.add(locationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1840, -1, -1));

        eventsData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/data.png"))); // NOI18N
        jPanel1.add(eventsData, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1820, -1, -1));

        eventsLbl1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        eventsLbl1.setForeground(new java.awt.Color(28, 94, 56));
        eventsLbl1.setText("EVENTS");
        jPanel1.add(eventsLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1780, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(28, 94, 56));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1180, 1000, 20));

        officersData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/data.png"))); // NOI18N
        jPanel1.add(officersData, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1270, -1, -1));

        possitionLbl1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 18)); // NOI18N
        possitionLbl1.setForeground(new java.awt.Color(28, 94, 56));
        possitionLbl1.setText("OFFICER POSITIONS");
        jPanel1.add(possitionLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1230, -1, -1));

        upcomingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/upcomingBtn.png"))); // NOI18N
        upcomingBtn.setBorder(null);
        upcomingBtn.setBorderPainted(false);
        upcomingBtn.setContentAreaFilled(false);
        upcomingBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/upcomingHover.png"))); // NOI18N
        upcomingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcomingBtnActionPerformed(evt);
            }
        });
        jPanel1.add(upcomingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 1770, -1, -1));

        completedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/completedBtn.png"))); // NOI18N
        completedBtn.setBorder(null);
        completedBtn.setBorderPainted(false);
        completedBtn.setContentAreaFilled(false);
        completedBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/completedHover.png"))); // NOI18N
        completedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedBtnActionPerformed(evt);
            }
        });
        jPanel1.add(completedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 1770, -1, -1));

        allBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/allBtn.png"))); // NOI18N
        allBtn.setBorder(null);
        allBtn.setBorderPainted(false);
        allBtn.setContentAreaFilled(false);
        allBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ChoosenOrg/AllHoverSmall.png"))); // NOI18N
        allBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBtnActionPerformed(evt);
            }
        });
        jPanel1.add(allBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 1770, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studOrgBtnActionPerformed

        new studOrgs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studOrgBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        //darkPanel.setVisible(true);
        //settingsPanel.setVisible(true);
        //settingsPanel.setLocation(750, 0);  wala pa settings
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:
new aboutBOND().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void completedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completedBtnActionPerformed

    private void allBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allBtnActionPerformed

    private void upcomingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcomingBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upcomingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choosenOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choosenOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choosenOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choosenOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choosenOrg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton allBtn;
    private javax.swing.JLabel authors;
    private javax.swing.JLabel bar;
    private javax.swing.JLabel bulsuBlur;
    private javax.swing.JButton completedBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel eventsData;
    private javax.swing.JLabel eventsLb2;
    private javax.swing.JLabel eventsLbl1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel locationLbl;
    private javax.swing.JTextArea missionArea;
    private javax.swing.JLabel missionLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel officersData;
    private javax.swing.JLabel possitionLbl1;
    private javax.swing.JLabel possitionLbl2;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JButton studOrgBtn;
    private javax.swing.JLabel termLbl;
    private javax.swing.JButton upcomingBtn;
    private javax.swing.JTextArea visionArea;
    private javax.swing.JLabel visionLbl;
    // End of variables declaration//GEN-END:variables
}
